version: '3.8'

services:
  iprofile-jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iprofile-jenkins
    restart: always
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jaguirre/.kube/config:/var/jenkins_home/.kube/config

volumes:
  jenkins_home:
